# Generated by Django 5.2.17 on 2026-09-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='audience',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
