# Generated by Django 5.2.17 on 2026-09-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agenttoken_audience'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='oauth.oauthclient'),
        ),
    ]
