# Generated by Django 5.2.17 on 2026-09-11 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agenttoken_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('secret_hash', models.CharField(blank=True, default='', max_length=64)),
                ('redirect_uris', models.JSONField(default=list)),
                ('registered_dynamically', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oauth_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=2000)),
                ('code_challenge', models.CharField(max_length=128)),
                ('resource', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='agents.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='oauth.oauthclient')),
            ],
            options={
                'db_table': 'oauth_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('refresh_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('resource', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshes', to='agents.agenttoken')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='agents.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='oauth.oauthclient')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_tokens', to='oauth.authorizationcode')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='oauth.refreshtoken')),
            ],
            options={
                'db_table': 'oauth_refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
