# Generated by Django 5.2.17 on 2026-09-10 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('drive', '0007_collection_chunk_overlap_words_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentQuery',
            fields=[
                ('query_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('source', models.CharField(choices=[('api', 'Search endpoint'), ('mcp', 'MCP server')], max_length=8)),
                ('limit', models.PositiveIntegerField()),
                ('result_count', models.PositiveIntegerField()),
                ('collections_searched', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='agents.agent')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='drive.folder')),
            ],
            options={
                'db_table': 'agent_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='agent_queries_agent_idx'), models.Index(fields=['-created_at'], name='agent_queries_recent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ['api', 'mcp'])), name='agent_queries_source_in_choices')],
            },
        ),
    ]
