# Generated by Django 5.2.17 on 2026-09-07 09:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, hyphens and underscores', regex='^[a-z0-9][a-z0-9_-]*$')])),
                ('provider', models.CharField(choices=[('local', 'Local'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('cohere', 'Cohere')], max_length=16)),
                ('model_name', models.CharField(max_length=200)),
                ('vector_size', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='collections_single_default')],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='drive.collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='drive.folder')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('storage_key', models.CharField(max_length=1024)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('processing_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], max_length=16, null=True)),
                ('is_agent_active', models.BooleanField(default=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='drive.folder')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='folders_unique_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_agent_active'], name='documents_agent_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('folder', 'name'), name='documents_unique_name_per_folder'),
        ),
    ]
