# Generated by Django 5.2.17 on 2026-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_default_collection_and_root_folder'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['local', 'openai', 'gemini', 'cohere'])), name='collections_provider_in_choices'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('processing_status__in', ['pending', 'processing', 'ready', 'failed']), ('processing_status__isnull', True), _connector='OR'), name='documents_status_in_choices'),
        ),
    ]
