# Generated by Django 5.2.17 on 2026-09-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_closed_enum_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='collections_provider_in_choices',
        ),
        migrations.AddField(
            model_name='collection',
            name='base_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='collection',
            name='provider',
            field=models.CharField(choices=[('local', 'Local model'), ('api', 'API endpoint')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['local', 'api'])), name='collections_provider_in_choices'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('provider', 'local'), models.Q(('base_url', ''), _negated=True), _connector='OR'), name='collections_api_requires_base_url'),
        ),
    ]
