# Generated by Django 5.2.17 on 2026-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_vendor_neutral_provider'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('parent',), name='folders_only_one_root', nulls_distinct=False),
        ),
    ]
