# Generated by Django 5.2.17 on 2026-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_collection_collections_unique_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='chunk_overlap_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='chunk_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('chunk_words__isnull', True), ('chunk_overlap_words__isnull', True), ('chunk_overlap_words__lt', models.F('chunk_words')), _connector='OR'), name='collections_overlap_below_chunk'),
        ),
    ]
