# Generated by Django 5.2.17 on 2026-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_collection_chunk_overlap_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='passage_prefix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='query_prefix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
