# Generated by Django 5.2.17 on 2026-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_collection_passage_prefix_collection_query_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
