# Generated by Django 5.2.17 on 2026-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0009_collection_encrypted_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='max_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='minimum_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
