# Generated by Django 5.2.17 on 2026-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_closed_enum_constraints'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'ready', 'failed'])), name='processing_jobs_status_in_choices'),
        ),
    ]
