# Generated by Django 5.2.17 on 2026-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_closed_enum_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
