# Generated by Django 5.2.17 on 2026-09-07 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='agents.agent')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='drive.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='drive.folder')),
            ],
            options={
                'db_table': 'permissions',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('folder__isnull', False)), models.Q(('document__isnull', False), ('folder__isnull', True)), _connector='OR'), name='permissions_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('agent', 'folder'), name='permissions_unique_agent_folder'), models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('agent', 'document'), name='permissions_unique_agent_document')],
            },
        ),
    ]
