# Generated by Django 5.2.17 on 2026-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('agents', '0001_initial'),
        ('drive', '0003_closed_enum_constraints'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['allow', 'deny'])), name='permissions_effect_in_choices'),
        ),
    ]
