# Generated by Django 5.2.17 on 2026-09-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_closed_enum_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['-created_at', 'permission_id']},
        ),
    ]
